=== BlackAndWhiteScallion/legeclodb/src/assets/schema_chr.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "uid",
      "name"
    ],
    "additionalProperties": false,
    "properties": {
      "uid": { "type": "string" },
      "icon": { "type": "string" },
      "name": { "type": "string" },
      "date": { "type": "string" },
      "desc": { "type": "string" },
      "descs": { "type": "object" },
      "slot": { "$ref": "schema_skill.json#/$defs/equipType" },
      "rarity": { "$ref": "schema_skill.json#/$defs/rarityType" },
      "class": { "$ref": "schema_skill.json#/$defs/unitType" },
      "symbol": { "$ref": "schema_skill.json#/$defs/symbolType" },
      "supportType": { "$ref": "schema_skill.json#/$defs/supportlType" },
      "damageType": { "$ref": "schema_skill.json#/$defs/damageType" },
      "range": { "type": "integer" },
      "move": { "type": "integer" },
      "shape": { "type": "array" },
      "statusInit": { "type": "array" },
      "statusLv": { "type": "array" },
      "statusStar": { "type": "array" },
      "statusTable": { "type": "object" },
      "talent": { "type": "string" },
      "skills": {
        "type": "array",
        "items": { "type": "string" }
      },
      "engage": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "date": { "type": "string" },
          "skills": {
            "type": "array",
            "items": { "type": "string" }
          }
        }
      },
      "tags": {
        "type": "array",
        "items": { "type": "string" }
      },
      "note": { "type": "string" }
    }
  }
}

=== BlackAndWhiteScallion/legeclodb/src/assets/npc_main_characters.json
[
  {
    "uid": "Ch904300305",
    "icon": "Ch400500401",
    "name": "魔術剣兵",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 379, 34, 20, 19, 15, 23 ],
      "10": [ 883, 69, 36, 32, 28, 45 ],
      "20": [ 1354, 103, 52, 44, 41, 66 ],
      "30": [ 2005, 147, 73, 67, 59, 85 ],
      "40": [ 2600, 193, 94, 91, 77, 105 ],
      "50": [ 3412, 256, 125, 123, 104, 135 ],
      "60": [ 4292, 322, 157, 160, 132, 163 ],
      "70": [ 5355, 404, 197, 204, 167, 199 ],
      "80": [ 6913, 517, 250, 255, 212, 257 ],
      "90": [ 8029, 599, 289, 287, 243, 305 ],
      "100": [ 9384, 699, 336, 326, 281, 364 ],
      "110": [ 13567, 742, 355, 340, 297, 389 ],
      "120": [ 17939, 784, 374, 355, 312, 415 ]
    },
    "talent": "3100122",
    "skills": [ "1100010", "1100011", "1200050" ]
  },
  {
    "uid": "Ch904300305ex1",
    "icon": "Ch400500401",
    "name": "魔術剣兵・改",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 454, 40, 24, 23, 18, 27 ],
      "10": [ 1060, 83, 43, 38, 34, 54 ],
      "20": [ 1625, 124, 62, 53, 49, 79 ],
      "30": [ 2406, 176, 88, 80, 71, 102 ],
      "40": [ 3120, 232, 113, 109, 92, 126 ],
      "50": [ 4094, 307, 150, 148, 125, 162 ],
      "60": [ 5150, 386, 188, 192, 158, 196 ],
      "70": [ 6426, 485, 236, 245, 200, 239 ],
      "80": [ 8296, 620, 300, 306, 254, 308 ],
      "90": [ 9635, 719, 347, 344, 292, 366 ],
      "100": [ 11261, 839, 403, 391, 337, 437 ],
      "110": [ 16280, 890, 426, 408, 356, 467 ],
      "120": [ 21527, 941, 449, 426, 374, 498 ],
      "130": [ 23680, 991, 472, 443, 394, 528 ]
    },
    "talent": "3100504",
    "skills": [ "1100010", "1100011", "1200050" ]
  },
  {
    "uid": "Ch903700305",
    "icon": "Ch903700305",
    "name": "冥気体",
    "class": "ソーサラー",
    "damageType": "マジック",
    "range": 0,
    "move": 3,
    "statusTable": {
      "1": [ 301, 20, 17, 35, 22, 16 ],
      "10": [ 778, 33, 30, 73, 38, 23 ],
      "20": [ 1220, 45, 43, 110, 54, 30 ],
      "30": [ 1845, 69, 61, 157, 75, 37 ],
      "40": [ 2415, 93, 80, 206, 97, 44 ],
      "50": [ 3186, 126, 107, 273, 128, 55 ],
      "60": [ 4028, 163, 136, 343, 162, 65 ],
      "70": [ 5043, 209, 171, 431, 202, 78 ],
      "80": [ 6518, 261, 216, 552, 256, 99 ],
      "90": [ 7568, 293, 248, 640, 295, 116 ],
      "100": [ 8841, 333, 287, 749, 343, 137 ],
      "110": [ 13098, 348, 303, 795, 363, 146 ],
      "120": [ 17548, 363, 319, 841, 382, 154 ]
    },
    "talent": "3100123",
    "skills": [ "1200051" ]
  },
  {
    "uid": "Ch508500499summon",
    "icon": "Ch400700401",
    "name": "ゴールデンボックス",
    "class": "ヴォイド",
    "damageType": "アタック",
    "range": 1,
    "move": 2,
    "statusTable": {
      "1": [ 355, 32, 20, 32, 20, 24 ],
      "10": [ 880, 69, 35, 69, 35, 26 ],
      "20": [ 1369, 104, 49, 104, 49, 28 ],
      "30": [ 2039, 149, 68, 149, 68, 30 ],
      "40": [ 2654, 197, 89, 197, 89, 32 ],
      "50": [ 3493, 262, 118, 262, 118, 36 ],
      "60": [ 4399, 330, 149, 330, 149, 39 ],
      "70": [ 5495, 415, 186, 415, 186, 44 ],
      "80": [ 7103, 532, 236, 532, 236, 52 ],
      "90": [ 8263, 617, 271, 617, 271, 58 ],
      "100": [ 9669, 722, 315, 722, 315, 66 ],
      "110": [ 11070, 766, 332, 766, 332, 68 ],
      "120": [ 12665, 810, 350, 810, 350, 70 ]
    },
    "talent": "3100276",
    "skills": [ "1100244" ]
  },
  {
    "uid": "Ch905200303",
    "icon": "Ch905200303",
    "name": "戦陣兵",
    "class": "ライダー",
    "damageType": "アタック",
    "range": 1,
    "move": 5,
    "statusTable": {
      "1": [ 446, 42, 25, 20, 19, 28 ],
      "10": [ 950, 79, 41, 32, 32, 42 ],
      "20": [ 1457, 117, 59, 46, 46, 58 ],
      "30": [ 2142, 165, 81, 70, 66, 74 ],
      "40": [ 2776, 215, 105, 96, 86, 89 ],
      "50": [ 3644, 285, 140, 130, 116, 113 ],
      "60": [ 4577, 358, 176, 169, 148, 135 ],
      "70": [ 5708, 449, 220, 217, 186, 164 ],
      "80": [ 7369, 574, 280, 272, 236, 211 ],
      "90": [ 8570, 666, 323, 306, 271, 249 ],
      "100": [ 10029, 779, 376, 349, 314, 295 ],
      "110": [ 11527, 827, 398, 365, 332, 315 ],
      "120": [ 13238, 875, 419, 381, 350, 335 ]
    },
    "talent": "3100289",
    "skills": [ "1200010" ]
  },
  {
    "uid": "Ch905300301",
    "icon": "Ch905300301",
    "name": "新選組隊士",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 469, 44, 24, 25, 18, 28 ],
      "10": [ 1000, 82, 40, 38, 31, 49 ],
      "20": [ 1533, 122, 57, 52, 45, 72 ],
      "30": [ 2244, 172, 79, 77, 64, 93 ],
      "40": [ 2904, 225, 103, 105, 84, 116 ],
      "50": [ 3811, 299, 136, 141, 113, 148 ],
      "60": [ 4780, 375, 171, 183, 144, 179 ],
      "70": [ 5958, 471, 215, 233, 181, 219 ],
      "80": [ 7695, 602, 273, 292, 230, 283 ],
      "90": [ 8959, 699, 314, 329, 264, 336 ],
      "100": [ 10494, 818, 366, 375, 306, 400 ],
      "110": [ 12025, 869, 387, 392, 323, 428 ],
      "120": [ 13771, 919, 408, 410, 340, 456 ]
    },
    "talent": "3100300",
    "skills": [ "1100047", "1100043", "1200049" ]
  },
  {
    "uid": "Ch905400301",
    "icon": "Ch905400301",
    "name": "謎の新選組隊士",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 491, 65, 25, 38, 19, 28 ],
      "10": [ 1048, 123, 41, 56, 32, 50 ],
      "20": [ 1606, 183, 58, 78, 45, 73 ],
      "30": [ 2341, 252, 80, 110, 65, 94 ],
      "40": [ 3028, 329, 104, 148, 85, 117 ],
      "50": [ 3974, 436, 137, 200, 114, 150 ],
      "60": [ 4979, 545, 173, 256, 145, 181 ],
      "70": [ 6204, 682, 216, 326, 183, 221 ],
      "80": [ 8014, 873, 275, 408, 232, 286 ],
      "90": [ 9338, 1019, 317, 463, 266, 339 ],
      "100": [ 10946, 1198, 369, 533, 309, 404 ],
      "110": [ 12550, 1273, 391, 559, 326, 432 ],
      "120": [ 14379, 1348, 412, 585, 344, 461 ]
    },
    "talent": "3100300",
    "skills": [ "1100047", "1100049", "1200049" ]
  },
  {
    "uid": "Ch905300301eg",
    "icon": "Ch905300301",
    "name": "新選組隊士・改",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 563, 53, 29, 30, 22, 34 ],
      "10": [ 1200, 98, 48, 46, 37, 59 ],
      "20": [ 1840, 146, 68, 62, 54, 86 ],
      "30": [ 2693, 206, 95, 92, 77, 112 ],
      "40": [ 3485, 270, 124, 126, 101, 139 ],
      "50": [ 4573, 359, 163, 169, 136, 178 ],
      "60": [ 5736, 450, 205, 220, 173, 215 ],
      "70": [ 7150, 565, 258, 280, 217, 263 ],
      "80": [ 9234, 722, 328, 350, 276, 340 ],
      "90": [ 10751, 839, 377, 395, 317, 403 ],
      "100": [ 12593, 982, 439, 450, 367, 480 ],
      "110": [ 14430, 1043, 464, 470, 388, 514 ],
      "120": [ 16525, 1103, 490, 492, 408, 547 ],
      "130": [ 18934, 1165, 517, 520, 431, 578 ]
    },
    "talent": "3100518",
    "skills": [ "1100047", "1100043", "1200049" ]
  },
  {
    "uid": "Ch905400301eg",
    "icon": "Ch905400301",
    "name": "謎の新選組隊士・改",
    "class": "ソルジャー",
    "damageType": "アタック",
    "range": 1,
    "move": 3,
    "statusTable": {
      "1": [ 589, 78, 30, 46, 23, 34 ],
      "10": [ 1258, 148, 49, 67, 38, 60 ],
      "20": [ 1927, 220, 70, 94, 54, 88 ],
      "30": [ 2809, 302, 96, 132, 78, 113 ],
      "40": [ 3634, 395, 125, 178, 102, 140 ],
      "50": [ 4769, 523, 164, 240, 137, 180 ],
      "60": [ 5975, 654, 208, 307, 174, 217 ],
      "70": [ 7445, 818, 259, 391, 220, 265 ],
      "80": [ 9617, 1048, 330, 490, 278, 343 ],
      "90": [ 11206, 1223, 380, 556, 319, 407 ],
      "100": [ 13135, 1438, 443, 640, 371, 485 ],
      "110": [ 15060, 1528, 469, 671, 391, 518 ],
      "120": [ 17255, 1618, 494, 702, 413, 553 ],
      "130": [ 19770, 1708, 522, 741, 436, 584 ]
    },
    "talent": "3100518",
    "skills": [ "1100047", "1100049", "1200049" ]
  },
  {
    "uid": "Ch516200499",
    "icon": "Ch516200499",
    "name": "賢者の石",
    "class": "ソーサラー",
    "damageType": "マジック",
    "range": 3,
    "move": 1,
    "statusTable": {
      "1": [ 491, 38, 25, 65, 19, 28 ],
      "10": [ 1100, 43, 39, 104, 54, 33 ],
      "20": [ 1725, 59, 56, 155, 77, 43 ],
      "30": [ 2527, 86, 78, 217, 104, 52 ],
      "40": [ 3291, 117, 102, 283, 133, 62 ],
      "50": [ 4340, 157, 136, 376, 177, 78 ],
      "60": [ 5449, 203, 172, 470, 221, 92 ],
      "70": [ 6801, 258, 216, 589, 276, 110 ],
      "80": [ 8804, 324, 274, 755, 350, 140 ],
      "90": [ 10289, 366, 316, 881, 405, 164 ],
      "100": [ 12090, 418, 367, 1034, 473, 194 ],
      "110": [ 13989, 438, 388, 1099, 501, 206 ],
      "120": [ 16162, 457, 408, 1164, 528, 218 ]
    },
    "talent": "3100381",
    "skills": [ "1100034", "1100061", "1200002" ]
  },
  {
    "uid": "Ch906000300",
    "icon": "Ch906000300",
    "name": "ファラオに従いし魂",
    "class": "ライダー",
    "damageType": "アタック",
    "range": 1,
    "move": 5,
    "statusTable": {
      "1": [ 467, 69, 25, 34, 19, 28 ],
      "10": [ 996, 130, 41, 53, 32, 43 ],
      "20": [ 1526, 192, 58, 75, 45, 60 ],
      "30": [ 2234, 264, 80, 108, 65, 76 ],
      "40": [ 2894, 344, 104, 147, 85, 92 ],
      "50": [ 3799, 455, 137, 199, 114, 117 ],
      "60": [ 4766, 567, 173, 256, 145, 139 ],
      "70": [ 5942, 709, 216, 326, 183, 169 ],
      "80": [ 7672, 908, 275, 410, 232, 217 ],
      "90": [ 8930, 1061, 317, 466, 266, 256 ],
      "100": [ 10459, 1247, 369, 537, 309, 304 ],
      "110": [ 12028, 1326, 391, 563, 326, 325 ],
      "120": [ 13821, 1404, 412, 590, 344, 345 ],
      "130": [ 14494, 1483, 433, 617, 361, 366 ]
    },
    "talent": "3100451",
    "skills": [ "1100053", "1200021", "1200031" ]
  },
  {
    "uid": "Ch906200300",
    "icon": "Ch906200300",
    "name": "バットミミック",
    "class": "アサシン",
    "damageType": "アタック",
    "range": 2,
    "move": 3,
    "statusTable": {
      "1": [ 471, 58, 21, 20, 19, 75 ],
      "10": [ 1119, 125, 34, 31, 33, 114 ],
      "20": [ 1755, 192, 49, 44, 48, 159 ],
      "30": [ 2569, 268, 69, 67, 68, 200 ],
