=== BlackAndWhiteScallion/legeclodb/src/assets/schema_item.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "/schemas/item",

  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "uid",
      "name"
    ],
    "additionalProperties": false,
    "properties": {
      "uid": { "type": "string" },
      "icon": { "type": "string" },
      "name": { "type": "string" },
      "date": { "type": "string" },
      "desc": { "type": "string" },
      "descs": { "type": "object" },
      "slot": { "type": "string" },
      "rarity": { "type": "string" },
      "classes": { "type": "array" },
      "statusInit": { "type": "array" },
      "statusLv": { "type": "array" },
      "amuletType": { "enum": [ "月", "太陽" ] },
      "buff": {
        "type": "array",
        "items": {
          "$ref": "schema_skill.json#/$defs/effect"
        }
      },
      "debuff": {
        "type": "array",
        "items": {
          "$ref": "schema_skill.json#/$defs/effect"
        }
      },
      "immune": {
        "type": "array",
        "items": {
          "$ref": "schema_skill.json#/$defs/effect"
        }
      },
      "statusEffects": {
        "type": "array",
        "items": {
          "$ref": "schema_skill.json#/$defs/effect"
        }
      },
      "drawback": {
        "type": "array",
        "items": {
          "$ref": "schema_skill.json#/$defs/effect"
        }
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "note": { "type": "string" }
    }
  }
}

=== BlackAndWhiteScallion/legeclodb/src/assets/main_passive.json
[
  {
    "uid": "クラス特性:ソルジャー(メイン)",
    "name": "クラス特性:ソルジャー(メイン)",
    "icon": "ソルジャー",
    "desc": "与ダメージ+20%。\nメインが「ランサー」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「ライダー」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ライダー" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ライダー" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:ランサー(メイン)",
    "name": "クラス特性:ランサー(メイン)",
    "icon": "ランサー",
    "desc": "与ダメージ+20%。\nメインが「ライダー」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「ソルジャー」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ライダー" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ライダー" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:ライダー(メイン)",
    "name": "クラス特性:ライダー(メイン)",
    "icon": "ライダー",
    "desc": "与ダメージ+20%。\nメインが「ソルジャー」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「ランサー」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:エアリアル(メイン)",
    "name": "クラス特性:エアリアル(メイン)",
    "icon": "エアリアル",
    "desc": "与ダメージ+20%。\nメインが「アサシン」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「シューター」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "アサシン" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "アサシン" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "シューター" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "シューター" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:ソーサラー(メイン)",
    "name": "クラス特性:ソーサラー(メイン)",
    "icon": "ソーサラー",
    "desc": "メインが「ソルジャー/ランサー/ライダー」の敵ユニットに攻撃時、メインのアタック/マジック+35%。メインが「エアリアル/アサシン/シューター」の敵ユニットに攻撃時、メインのアタック/マジック-15%",
    "buff": [
      {
        "type": "アタック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー", "ランサー", "ライダー" ]
        }
      },
      {
        "type": "マジック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー", "ランサー", "ライダー" ]
        }
      },
      {
        "type": "アタック",
        "value": -15,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル", "アサシン", "シューター" ]
        }
      },
      {
        "type": "マジック",
        "value": -15,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル", "アサシン", "シューター" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:セイント(メイン)",
    "name": "クラス特性:セイント(メイン)",
    "icon": "セイント",
    "desc": "メインが「エアリアル/アサシン/シューター」の敵ユニットに攻撃時、メインのアタック/マジック+35%。メインが「ソルジャー/ランサー/ライダー」の敵ユニットに攻撃時、メインのアタック/マジック-15%",
    "buff": [
      {
        "type": "アタック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル", "アサシン", "シューター" ]
        }
      },
      {
        "type": "マジック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル", "アサシン", "シューター" ]
        }
      },
      {
        "type": "アタック",
        "value": -15,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー", "ランサー", "ライダー" ]
        }
      },
      {
        "type": "マジック",
        "value": -15,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ソルジャー", "ランサー", "ライダー" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:シューター(メイン)",
    "name": "クラス特性:シューター(メイン)",
    "icon": "シューター",
    "desc": "与ダメージ+20%。\nメインが「エアリアル」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「アサシン」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "アサシン" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "アサシン" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:アサシン(メイン)",
    "name": "クラス特性:アサシン(メイン)",
    "icon": "アサシン",
    "desc": "与ダメージ+20%。\nメインが「シューター」の敵ユニットに攻撃時、メインのアタック/マジック+75%。メインが「エアリアル」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "与ダメージ",
        "value": 20,
        "target": "自身(メイン)"
      },
      {
        "type": "アタック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "シューター" ]
        }
      },
      {
        "type": "マジック",
        "value": 75,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "シューター" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル" ]
        }
      },
      {
        "type": "マジック",
        "value": -35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "エアリアル" ]
        }
      }
    ]
  },
  {
    "uid": "クラス特性:ソルジャー(敵メイン)",
    "name": "クラス特性:ソルジャー(敵メイン)",
    "icon": "ソルジャー",
    "desc": "メインが「ランサー」の敵ユニットに攻撃時、メインのアタック/マジック+35%。メインが「ライダー」の敵ユニットに攻撃時、メインのアタック/マジック-35%",
    "buff": [
      {
        "type": "アタック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      },
      {
        "type": "マジック",
        "value": 35,
        "ephemeral": true,
        "target": "自身(メイン)",
        "timing": "攻撃前",
        "condition": {
          "onTargetClass": [ "ランサー" ]
        }
      },
      {
        "type": "アタック",
        "value": -35,
